// middleware types
export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'
export const REGISTER = 'REGISTER'

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED'
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const TODOS_INDEX = 'TODOS_INDEX'
export const TODOS_INDEX_SUCCEEDED = 'TODOS_INDEX_SUCCEEDED'
export const TODOS_INDEX_FAILED = 'TODOS_INDEX_FAILED'

export const TODOS_CLEAR_COMPLETED = 'TODOS_CLEAR_COMPLETED'
export const TODOS_CLEAR_COMPLETED_SUCCEEDED = 'TODOS_CLEAR_COMPLETED_SUCCEEDED'
export const TODOS_CLEAR_COMPLETED_FAILED = 'TODOS_CLEAR_COMPLETED_FAILED'

export const TODOS_TOGGLE_STATUS = 'TODOS_TOGGLE_STATUS'
export const TODOS_TOGGLE_STATUS_SUCCEEDED = 'TODOS_TOGGLE_STATUS_SUCCEEDED'
export const TODOS_TOGGLE_STATUS_FAILED = 'TODOS_TOGGLE_STATUS_FAILED'

export const TODO_CREATE = 'TODO_CREATE'
export const TODO_CREATE_SUCCEEDED = 'TODO_CREATE_SUCCEEDED'
export const TODO_CREATE_FAILED = 'TODO_CREATE_FAILED'

export const TODO_UPDATE = 'TODO_UPDATE'
export const TODO_UPDATE_SUCCEEDED = 'TODO_UPDATE_SUCCEEDED'
export const TODO_UPDATE_FAILED = 'TODO_UPDATE_FAILED'

export const TODO_DELETE = 'TODO_DELETE'
export const TODO_DELETE_SUCCEEDED = 'TODO_DELETE_SUCCEEDED'
export const TODO_DELETE_FAILED = 'TODO_DELETE_FAILED'
